targets = [
  "host1", "host2"
]

[default]
fetch_lines_limit = 9

[default.ssh]
username = "root"
password = "vagrant"
keys = [ "/home/studio3104/.ssh/id_rsa" ]
passphrase = ""
port = 20022

[default.mysql]
username = "nata"
password = "nata"
port = 13306

# settings per targets
[host1.ssh]
username = "satoshi"
keys = [ "/home/satoshi/.ssh/id_rsa" ]
passphrase = ""
