[targets]
service1 = [ "host1", "host2" ]
service2 = [ "host3", "host4" ]

[nataserver]
fqdn = "locahost"
port = 9393

[default]
fetch_lines_limit = 9

[default.ssh]
username = "root"
password = "vagrant"
keys = [ "/home/studio3104/.ssh/id_rsa" ]
passphrase = ""
port = 20022

[default.mysql]
username = "nata"
password = "nata"
port = 13306

# settings per targets
[host1.ssh]
username = "satoshi"
keys = [ "/home/satoshi/.ssh/id_rsa" ]
passphrase = ""
